import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "./Components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DocoBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Varela+Round&display=swap');
        </style>
      </Head>
      <main>
        <NavBar></NavBar>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
